import turtle

wn = turtle.Screen()
wn.bgcolor("white")
t = turtle.Turtle()
t.speed(0)
# position the cursor
# t.penup()
t.pensize(4)


def square():
    for x in range(4):
        t.forward(20)
        t.right(90)

def Pac_Man():
    t.penup()
    t.right(90)
    t.backward(20)
    t.pendown()

    for x in range(3):
        t.begin_fill()
        square()
        t.forward(20)
        t.color("Yellow")
        t.end_fill()
        t.color("Black")
    t.forward(20)
    t.right(180)
    for x in range(5):
        t.begin_fill()
        square()
        t.forward(20)
        t.color("Yellow")
        t.end_fill()
        t.color("Black")

    t.right(90)
    t.forward(40)
    t.right(90)
    for x in range(1):
        t.begin_fill()
        square()
        t.forward(20)
        t.color("Yellow")
        t.end_fill()
        t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Brown")
    t.end_fill()
    t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.right(180)
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.penup()
    t.forward(20)
    t.pendown()
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.begin_fill()
    square()
    t.forward(20)
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.right(90)
    t.forward(20)
    t.begin_fill()
    square()
    t.color("Yellow")
    t.end_fill()
    t.color("Black")
    t.right(90)
    t.penup()
    t.forward(80)
    t.pendown()
    t.left(90)
    t.begin_fill()
    square()
    t.color("Yellow")
    t.end_fill()
    t.color("Black")

Pac_Man()

turtle.done()